// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import type {PoissonLabMetrics} from './poisson-lab-engine';

export type PoissonLabMode = 'beauty' | 'engineering';

export function makePoissonLabPanelHtml(metrics: PoissonLabMetrics): string {
  return `<div data-poisson-lab>
<style>
[data-poisson-lab]{font:12px/1.45 system-ui,sans-serif;color:#eaf7ff}.poisson-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:12px}.poisson-tabs button{padding:8px;border-radius:7px;border:1px solid #31566c;background:#102838;color:#dff5ff;cursor:pointer}.poisson-tabs button[data-active=true]{background:#194663;border-color:#6ecbff}.poisson-metric{display:flex;justify-content:space-between;gap:16px;padding:5px 0;border-bottom:1px solid #173344}.poisson-value{font-variant-numeric:tabular-nums;color:#9ee7ff}.poisson-note{margin-top:12px;color:#9eb8c7}.poisson-proof{margin-top:12px;padding:10px;border:1px solid #31566c;border-radius:8px;background:#0b1e2a}.poisson-proof strong{color:#b9f3ff}
</style>
<div class="poisson-tabs"><button data-mode="beauty" data-active="true">Beauty</button><button data-mode="engineering">Engineering</button></div>
<div data-panel="beauty"><p>Orbit the solved potential surface. Contours reveal equal-potential lines; gradient traces follow the field generated by the source.</p><p class="poisson-note">Manufactured solution: <strong>u(x,y)=sin(πx)sin(πy)</strong></p></div>
<div data-panel="engineering" hidden>
${metric('Grid',`${metrics.resolution} × ${metrics.resolution}`)}
${metric('Unknowns',metrics.unknowns.toLocaleString())}
${metric('CSR nonzeros',metrics.nonZeros.toLocaleString())}
${metric('Graph nodes',String(metrics.graphNodes))}
${metric('SpMV strategy',metrics.spmvStrategy)}
${metric('Preconditioner',metrics.preconditioner)}
${metric('Iterations',formatNullable(metrics.iterations))}
${metric('Relative residual',formatScientific(metrics.relativeResidual))}
${metric('Relative solution error',formatScientific(metrics.relativeError))}
<div class="poisson-proof"><strong>Correctness contract</strong><br/>Residual and error remain explicitly unavailable until measured from the real solver. The showcase never substitutes simulated convergence metrics.</div>
</div></div>`;
}

export function bindPoissonLabPanel(root: HTMLElement, onMode: (mode: PoissonLabMode) => void): void {
  const buttons=[...root.querySelectorAll<HTMLButtonElement>('[data-mode]')];
  const panels=[...root.querySelectorAll<HTMLElement>('[data-panel]')];
  for(const button of buttons){button.onclick=()=>{const mode=button.dataset.mode as PoissonLabMode;for(const item of buttons)item.dataset.active=String(item===button);for(const panel of panels)panel.hidden=panel.dataset.panel!==mode;onMode(mode);};}
}

function metric(label:string,value:string):string{return `<div class="poisson-metric"><span>${label}</span><span class="poisson-value">${value}</span></div>`;}
function formatNullable(value:number|null):string{return value===null?'not yet published':String(value);}
function formatScientific(value:number|null):string{return value===null?'not yet measured':value.toExponential(3);}
