import GL from '@luma.gl/constants';

/** Parameters for textures and samplers */
export type WebGLSamplerParameters = {
  [GL.TEXTURE_WRAP_S]?: GL.CLAMP_TO_EDGE | GL.REPEAT | GL.MIRRORED_REPEAT;
  [GL.TEXTURE_WRAP_T]?: GL.CLAMP_TO_EDGE | GL.REPEAT | GL.MIRRORED_REPEAT;
  [GL.TEXTURE_WRAP_R]?: GL.CLAMP_TO_EDGE | GL.REPEAT | GL.MIRRORED_REPEAT;
  [GL.TEXTURE_MAG_FILTER]?: GL.NEAREST | GL.LINEAR;
  [GL.TEXTURE_MIN_FILTER]?: GL.NEAREST_MIPMAP_NEAREST | GL.NEAREST_MIPMAP_LINEAR | GL.LINEAR_MIPMAP_NEAREST | GL.LINEAR_MIPMAP_LINEAR;
  [GL.TEXTURE_MIN_LOD]?: number;
  [GL.TEXTURE_MAX_LOD]?: number;
  [GL.TEXTURE_COMPARE_FUNC]?: number; // COMPARE_FUNC);
  // [GL.TEXTURE_MAX_ANISOTROPY]?: number; //
};
