// luma.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import type {Binding, Bindings, ComputeShaderLayout, ShaderLayout} from '@luma.gl/core';
import {Buffer, Sampler, Texture, TextureView, getShaderLayoutBinding, log} from '@luma.gl/core';
import type {WebGPUDevice} from '../webgpu-device';
import type {WebGPUBuffer} from '../resources/webgpu-buffer';
import type {WebGPUSampler} from '../resources/webgpu-sampler';
import type {WebGPUTexture} from '../resources/webgpu-texture';
import type {WebGPUTextureView} from '../resources/webgpu-texture-view';

/**
 * Create a WebGPU "bind group layout" from an array of luma.gl bindings
 * @note bind groups can be automatically generated by WebGPU.
 */
export function makeBindGroupLayout(
  device: GPUDevice,
  layout: GPUBindGroupLayout,
  bindings: Bindings
): GPUBindGroupLayout {
  throw new Error('not implemented');
  // return device.createBindGroupLayout({
  //   layout,
  //   entries: getBindGroupEntries(bindings)
  // })
}

/**
 * Create a WebGPU "bind group" from an array of luma.gl bindings
 */
export function getBindGroup(
  device: WebGPUDevice,
  bindGroupLayout: GPUBindGroupLayout,
  shaderLayout: ShaderLayout | ComputeShaderLayout,
  bindings: Bindings,
  group: number
): GPUBindGroup | null {
  const entries = getBindGroupEntries(bindings, shaderLayout, group);
  if (entries.length === 0) {
    return null;
  }
  device.pushErrorScope('validation');
  const bindGroup = device.handle.createBindGroup({
    layout: bindGroupLayout,
    entries
  });
  device.popErrorScope((error: GPUError) => {
    log.error(`bindGroup creation: ${error.message}`, bindGroup)();
  });
  return bindGroup;
}

/**
 * @param bindings
 * @returns
 */
function getBindGroupEntries(
  bindings: Bindings,
  shaderLayout: ShaderLayout | ComputeShaderLayout,
  group: number
): GPUBindGroupEntry[] {
  const entries: GPUBindGroupEntry[] = [];

  for (const [bindingName, value] of Object.entries(bindings)) {
    const exactBindingLayout = shaderLayout.bindings.find(binding => binding.name === bindingName);
    const bindingLayout = exactBindingLayout || getShaderLayoutBinding(shaderLayout, bindingName);
    const isShadowedAlias =
      !exactBindingLayout && bindingLayout ? bindingLayout.name in bindings : false;

    // Mirror the WebGL path: when both `foo` and `fooUniforms` exist in the bindings map,
    // prefer the exact shader binding name and ignore the alias entry.
    if (!isShadowedAlias && bindingLayout?.group === group) {
      const entry = bindingLayout
        ? getBindGroupEntry(value, bindingLayout.location, undefined, bindingName)
        : null;
      if (entry) {
        entries.push(entry);
      }

      // TODO - hack to automatically bind samplers to supplied texture default samplers
      if (value instanceof Texture) {
        const samplerBindingLayout = getShaderLayoutBinding(shaderLayout, `${bindingName}Sampler`, {
          ignoreWarnings: true
        });
        const samplerEntry = samplerBindingLayout
          ? samplerBindingLayout.group === group
            ? getBindGroupEntry(value, samplerBindingLayout.location, {sampler: true}, bindingName)
            : null
          : null;
        if (samplerEntry) {
          entries.push(samplerEntry);
        }
      }
    }
  }

  return entries;
}

function getBindGroupEntry(
  binding: Binding,
  index: number,
  options?: {sampler?: boolean},
  bindingName: string = 'unknown'
): GPUBindGroupEntry | null {
  if (binding instanceof Buffer) {
    return {
      binding: index,
      resource: {
        buffer: (binding as WebGPUBuffer).handle
      }
    };
  }
  if (binding instanceof Sampler) {
    return {
      binding: index,
      resource: (binding as WebGPUSampler).handle
    };
  }
  if (binding instanceof TextureView) {
    return {
      binding: index,
      resource: (binding as WebGPUTextureView).handle
    };
  }
  if (binding instanceof Texture) {
    if (options?.sampler) {
      return {
        binding: index,
        resource: (binding as WebGPUTexture).sampler.handle
      };
    }
    return {
      binding: index,
      resource: (binding as WebGPUTexture).view.handle
    };
  }
  log.warn(`invalid binding ${bindingName}`, binding);
  return null;
}
