// luma.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import type {ComputeShaderLayout, BindingDeclaration, Binding} from '@luma.gl/core';
import {Buffer, Sampler, Texture, TextureView, log} from '@luma.gl/core';
import type {WebGPUDevice} from '../webgpu-device';
import type {WebGPUBuffer} from '../resources/webgpu-buffer';
import type {WebGPUSampler} from '../resources/webgpu-sampler';
import type {WebGPUTexture} from '../resources/webgpu-texture';
import type {WebGPUTextureView} from '../resources/webgpu-texture-view';

/**
 * Create a WebGPU "bind group layout" from an array of luma.gl bindings
 * @note bind groups can be automatically generated by WebGPU.
 */
export function makeBindGroupLayout(
  device: GPUDevice,
  layout: GPUBindGroupLayout,
  bindings: Binding[]
): GPUBindGroupLayout {
  throw new Error('not implemented');
  // return device.createBindGroupLayout({
  //   layout,
  //   entries: getBindGroupEntries(bindings)
  // })
}

/**
 * Create a WebGPU "bind group" from an array of luma.gl bindings
 */
export function getBindGroup(
  device: WebGPUDevice,
  bindGroupLayout: GPUBindGroupLayout,
  shaderLayout: ComputeShaderLayout,
  bindings: Record<string, Binding>
): GPUBindGroup {
  const entries = getBindGroupEntries(bindings, shaderLayout);
  device.pushErrorScope('validation');
  const bindGroup = device.handle.createBindGroup({
    layout: bindGroupLayout,
    entries
  });
  device.popErrorScope((error: GPUError) => {
    log.error(`bindGroup creation: ${error.message}`, bindGroup)();
  });
  return bindGroup;
}

export function getShaderLayoutBinding(
  shaderLayout: ComputeShaderLayout,
  bindingName: string,
  options?: {ignoreWarnings?: boolean}
): BindingDeclaration | null {
  const bindingLayout = shaderLayout.bindings.find(
    binding =>
      binding.name === bindingName ||
      `${binding.name.toLocaleLowerCase()}uniforms` === bindingName.toLocaleLowerCase()
  );
  if (!bindingLayout && !options?.ignoreWarnings) {
    log.warn(`Binding ${bindingName} not set: Not found in shader layout.`)();
  }
  return bindingLayout || null;
}

/**
 * @param bindings
 * @returns
 */
function getBindGroupEntries(
  bindings: Record<string, Binding>,
  shaderLayout: ComputeShaderLayout
): GPUBindGroupEntry[] {
  const entries: GPUBindGroupEntry[] = [];

  for (const [bindingName, value] of Object.entries(bindings)) {
    const exactBindingLayout = shaderLayout.bindings.find(binding => binding.name === bindingName);
    const bindingLayout = exactBindingLayout || getShaderLayoutBinding(shaderLayout, bindingName);
    const isShadowedAlias =
      !exactBindingLayout && bindingLayout ? bindingLayout.name in bindings : false;

    // Mirror the WebGL path: when both `foo` and `fooUniforms` exist in the bindings map,
    // prefer the exact shader binding name and ignore the alias entry.
    if (!isShadowedAlias) {
      const entry = bindingLayout
        ? getBindGroupEntry(value, bindingLayout.location, undefined, bindingName)
        : null;
      if (entry) {
        entries.push(entry);
      }

      // TODO - hack to automatically bind samplers to supplied texture default samplers
      if (value instanceof Texture) {
        const samplerBindingLayout = getShaderLayoutBinding(shaderLayout, `${bindingName}Sampler`, {
          ignoreWarnings: true
        });
        const samplerEntry = samplerBindingLayout
          ? getBindGroupEntry(value, samplerBindingLayout.location, {sampler: true}, bindingName)
          : null;
        if (samplerEntry) {
          entries.push(samplerEntry);
        }
      }
    }
  }

  return entries;
}

function getBindGroupEntry(
  binding: Binding,
  index: number,
  options?: {sampler?: boolean},
  bindingName: string = 'unknown'
): GPUBindGroupEntry | null {
  if (binding instanceof Buffer) {
    return {
      binding: index,
      resource: {
        buffer: (binding as WebGPUBuffer).handle
      }
    };
  }
  if (binding instanceof Sampler) {
    return {
      binding: index,
      resource: (binding as WebGPUSampler).handle
    };
  }
  if (binding instanceof TextureView) {
    return {
      binding: index,
      resource: (binding as WebGPUTextureView).handle
    };
  }
  if (binding instanceof Texture) {
    if (options?.sampler) {
      return {
        binding: index,
        resource: (binding as WebGPUTexture).sampler.handle
      };
    }
    return {
      binding: index,
      resource: (binding as WebGPUTexture).view.handle
    };
  }
  log.warn(`invalid binding ${bindingName}`, binding);
  return null;
}
