name: Bug Report
description: Something does not work as expected
title: "[Bug]"
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a bug!
- type: markdown
  attributes:
    value: |
      **Warning: In order to prevent drowning in unactionable issues, any issues that are not clearly actionable bugs will be closed immediately.** 
      luma.gl primarily uses [GitHub Discussions](https://github.com/visgl/luma.gl/discussions) 
      and the [Open Visualization OpenJS Foundation slack channels](https://www.openvisualization.org/#get-involved) to interact with users.
      GitHub Issues are for confirmed bugs only.
      
      Please start in the Discussions section rather than opening an issue if you are e.g.
      - not yet sure if you are hitting a bug or just using the APIs wrong
      - having issues with your particular build environment that are not yet clearly root caused,
      - wanting to discuss a new feature proposal 
- type: markdown
  attributes:
    value: |
      Tips: Before filing a new bug:
      Check [existing issues](https://github.com/visgl/luma.gl/issues)to avoid filing duplicate bugs.
      You may find answers faster by searching in [the documentation](https://luma.gl/search).
- type: markdown
  attributes:
    value: |
      "luma.gl" is developed and maintained by a group of individuals but we can only cover so much.
      We partly rely on the people who report bugs to make PRs for the fixes.
      If you choose to open PRs, the vis.gl / Open Visualization leads are focused on helping review and land your PRs, and publish new versions with your fixes.
      Simple fixes will generally land quickly if you are willing to address comments and fix linter issues.
- type: textarea
  id: flavor
  attributes:
    label: Module and/or Feature
    description: First, are you able to pinpoint which luma.gl module or feature is causing the issue?
- type: textarea
  attributes:
    label: Description
    description: What you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: What you expect to see.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Providing the following could help us resolve this issue faster:
        - A Codepen that reproduces the behavior. A good starting point is the "edit in CodePen" links in the layer documentations.
        - A sample of your dataset
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Example:
        - **Framework version**: luma.gl@4.2.0
        - **Browser**: Chrome 110.0
        - **Node**: Node 20.0
    value: |
        - Framework version:
        - Browser:
        - Node:
        - OS:
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: Check the browser console for any relevant errors or warnings.
  validations:
    required: false
