blank_issues_enabled: false
contact_links:
  - name: Start a Discussion: Open a GitHub Discussion (I have a question / I need help)
    url: https://github.com/visgl/loaders.gl/discussions
    about: Please ask generic questions or request help here in discussions. "Issues" are for confirmed bugs or approved feature requests.