// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import {Buffer, type Device} from '@luma.gl/core';
import {Model, type ModelProps} from '@luma.gl/engine';
import type {FontAtlas} from './atlas/font-atlas';
import {measureFontAtlasText} from './atlas/text-metrics';
import {GPUTextResources} from './gpu-text-resources';
import {buildTextGpuDictionaryCompressedStream} from './model-utils/text-layout';

const UINT32_BYTE_LENGTH = Uint32Array.BYTES_PER_ELEMENT;

/** Construction properties for a renderer that stores each distinct string only once. */
export type DictionaryTextRendererProps = {
  /** Unique strings referenced by application-owned row or glyph-occurrence records. */
  dictionary: readonly string[];
  /** Normalized atlas used to lay out and render the dictionary strings. */
  fontAtlas: FontAtlas;
  /** Text height in screen pixels. Defaults to 12. */
  fontSize?: number;
  /** Constant RGBA text color. Defaults to a restrained near-white. */
  color?: [number, number, number, number];
  /** Debug label for generated resources. */
  id?: string;
  /** Host shader and render-pipeline configuration. */
  modelProps: Omit<ModelProps, 'bindings' | 'vertexCount' | 'instanceCount'> & {
    bindings?: NonNullable<ModelProps['bindings']>;
  };
};

/**
 * GPU dictionary text resources plus a host-configured render model.
 *
 * Each dictionary string owns one shared glyph-layout run. Applications provide their own compact
 * visible-glyph occurrence stream, which can be generated by a GPU culling graph without expanding
 * every source row. The renderer exposes the dictionary metrics buffer to the culling stage and
 * dictionary glyph buffers to the render stage.
 */
export class DictionaryTextRenderer {
  readonly device: Device;
  readonly dictionary: readonly string[];
  readonly model: Model;
  readonly resources: GPUTextResources;
  /** `(glyphCount, bitcast<f32>(advancePixels))` per dictionary value. */
  readonly dictionaryMetrics: Buffer;
  readonly dictionaryGlyphRanges: Buffer;
  readonly dictionaryGlyphRecords: Buffer;
  readonly glyphFrames: Buffer;
  /** Constant color, glyph scale, SDF settings, and screen-space line height used by the host. */
  readonly styleUniforms: Buffer;
  readonly glyphCounts: Uint32Array;
  readonly advances: Float32Array;
  private destroyed = false;

  constructor(device: Device, props: DictionaryTextRendererProps) {
    if (device.type !== 'webgpu') {
      throw new Error('DictionaryTextRenderer requires a WebGPU device');
    }
    if (props.dictionary.length === 0) {
      throw new Error('DictionaryTextRenderer requires at least one dictionary value');
    }
    this.device = device;
    this.dictionary = [...props.dictionary];
    const id = props.id ?? 'dictionary-text-renderer';
    const fontSize = props.fontSize ?? 12;
    const color = props.color ?? [0.9, 0.93, 0.97, 0.94];
    const codePoints = this.dictionary.map(value =>
      Array.from(value, character => character.codePointAt(0)!)
    );
    const stream = buildTextGpuDictionaryCompressedStream(
      {
        rowCount: this.dictionary.length,
        dictionaryValueCount: this.dictionary.length,
        getRowDictionaryIndex: rowIndex => rowIndex,
        visitDictionaryCodePoints: (dictionaryIndex, visitCodePoint) =>
          codePoints[dictionaryIndex]?.forEach(visitCodePoint)
      },
      {
        fontAtlas: props.fontAtlas,
        textAnchor: 'start',
        alignmentBaseline: 'center'
      }
    );
    this.glyphCounts = new Uint32Array(this.dictionary.length);
    this.advances = new Float32Array(this.dictionary.length);
    const glyphScale = fontSize / Math.max(props.fontAtlas.lineHeight, 1);
    const metrics = new ArrayBuffer(this.dictionary.length * 2 * UINT32_BYTE_LENGTH);
    const metricWords = new Uint32Array(metrics);
    const metricFloats = new Float32Array(metrics);
    for (let dictionaryIndex = 0; dictionaryIndex < this.dictionary.length; dictionaryIndex++) {
      const rangeOffset = dictionaryIndex * 2;
      const glyphCount =
        (stream.dictionaryGlyphRanges[rangeOffset + 1] ?? 0) -
        (stream.dictionaryGlyphRanges[rangeOffset] ?? 0);
      const advance =
        measureFontAtlasText(this.dictionary[dictionaryIndex]!, props.fontAtlas).advance *
        glyphScale;
      this.glyphCounts[dictionaryIndex] = glyphCount;
      this.advances[dictionaryIndex] = advance;
      metricWords[rangeOffset] = glyphCount;
      metricFloats[rangeOffset + 1] = advance;
    }
    this.resources = new GPUTextResources(device, {id, fontAtlas: props.fontAtlas});
    this.dictionaryMetrics = createStorageBuffer(device, `${id}-metrics`, new Uint8Array(metrics));
    this.dictionaryGlyphRanges = createStorageBuffer(
      device,
      `${id}-glyph-ranges`,
      stream.dictionaryGlyphRanges
    );
    this.dictionaryGlyphRecords = createStorageBuffer(
      device,
      `${id}-glyph-records`,
      stream.dictionaryGlyphRecords
    );
    this.glyphFrames = createStorageBuffer(device, `${id}-glyph-frames`, stream.glyphFrames);
    const styleData = new ArrayBuffer(12 * UINT32_BYTE_LENGTH);
    const styleFloats = new Float32Array(styleData);
    const styleWords = new Uint32Array(styleData);
    styleFloats.set(color, 0);
    styleFloats[4] = glyphScale;
    styleFloats[5] = props.fontAtlas.renderSettings.threshold;
    styleFloats[6] = props.fontAtlas.renderSettings.smoothing;
    styleWords[7] = getFontRenderMode(props.fontAtlas.renderSettings.mode);
    styleFloats[8] = fontSize;
    this.styleUniforms = device.createBuffer({
      id: `${id}-style-uniforms`,
      byteLength: styleData.byteLength,
      usage: Buffer.UNIFORM | Buffer.COPY_DST
    });
    this.styleUniforms.write(styleData);
    this.model = new Model(device, {
      ...props.modelProps,
      id,
      topology: props.modelProps.topology ?? 'triangle-list',
      vertexCount: 6,
      instanceCount: 0,
      bindings: this.getBindings(props.modelProps.bindings)
    });
  }

  /** Returns shared dictionary bindings merged with application-owned occurrence bindings. */
  getBindings(
    bindings: NonNullable<ModelProps['bindings']> = {}
  ): NonNullable<ModelProps['bindings']> {
    return {
      ...bindings,
      textDictionaryGlyphRanges: this.dictionaryGlyphRanges,
      textDictionaryGlyphRecords: this.dictionaryGlyphRecords,
      textGlyphFrames: this.glyphFrames,
      textDictionaryStyle: this.styleUniforms,
      fontAtlasTexture: this.resources.atlasTexture
    };
  }

  destroy(): void {
    if (this.destroyed) {
      return;
    }
    this.destroyed = true;
    this.model.destroy();
    this.styleUniforms.destroy();
    this.glyphFrames.destroy();
    this.dictionaryGlyphRecords.destroy();
    this.dictionaryGlyphRanges.destroy();
    this.dictionaryMetrics.destroy();
    this.resources.destroy();
  }
}

function createStorageBuffer(
  device: Device,
  id: string,
  data: ArrayBuffer | ArrayBufferView
): Buffer {
  const byteLength = data.byteLength;
  return device.createBuffer({
    id,
    data: byteLength > 0 ? data : new Uint32Array(1),
    usage: Buffer.STORAGE | Buffer.COPY_DST
  });
}

function getFontRenderMode(mode: FontAtlas['renderSettings']['mode']): number {
  switch (mode) {
    case 'bitmap':
      return 0;
    case 'sdf':
      return 1;
    case 'msdf':
      return 2;
  }
}
