// luma.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import type {Buffer, TextureView} from '@luma.gl/core';
import type {ShaderModule, ShaderPlugin} from '@luma.gl/shadertools';

export type ABufferShaderModuleProps = {
  /** Whether the current draw should append fragments into the A-buffer. */
  isActive?: boolean;
  /** Width and height of the target framebuffer in device pixels. */
  framebufferSize?: [number, number];
  /** Top row of the horizontal slice currently being captured. */
  sliceStartY?: number;
  /** Per-pixel head pointers plus fragment counters. */
  headPointers?: Buffer;
  /** Packed translucent fragment records. */
  fragments?: Buffer;
  /** Opaque depth generated by the base pass. */
  opaqueDepthTexture?: TextureView;
};

/** Uniform values consumed by the {@link aBuffer} shader module. */
export type ABufferShaderModuleUniforms = {
  /** Whether capture is active for the current draw. */
  isActive: boolean;
  /** Width and height of the target framebuffer in device pixels. */
  framebufferSize: [number, number];
  /** Top row of the horizontal slice currently being captured. */
  sliceStartY: number;
};

/** Storage and texture bindings consumed by the {@link aBuffer} shader module. */
export type ABufferShaderModuleBindings = {
  /** Per-pixel linked-list heads and allocation counters. */
  headPointers?: Buffer;
  /** Packed premultiplied-color, depth, and next-pointer records. */
  fragments?: Buffer;
  /** Opaque depth sampled before allocating translucent fragment records. */
  opaqueDepthTexture?: TextureView;
};

// GPUShaderStage.FRAGMENT without requiring the WebGPU global on WebGL-only pages.
const SHADER_STAGE_FRAGMENT = 0x2;

const A_BUFFER_WGSL = /* wgsl */ `\
const A_BUFFER_EMPTY_FRAGMENT_POINTER: u32 = 0u;

struct ABufferUniforms {
  isActive: i32,
  framebufferSize: vec2<f32>,
  sliceStartY: i32,
};

struct ABufferHeadPointers {
  nextFragmentIndex: atomic<u32>,
  droppedFragmentCount: atomic<u32>,
  heads: array<atomic<u32>>,
};

struct ABufferFragment {
  color: u32,
  depth: f32,
  next: u32,
};

struct ABufferFragments {
  fragments: array<ABufferFragment>,
};

@group(0) @binding(auto) var<uniform> aBuffer: ABufferUniforms;
@group(0) @binding(auto) var<storage, read_write> headPointers: ABufferHeadPointers;
@group(0) @binding(auto) var<storage, read_write> fragments: ABufferFragments;
@group(0) @binding(auto) var opaqueDepthTexture: texture_depth_2d;

fn aBuffer_getPixelIndex(fragmentPosition: vec4<f32>) -> u32 {
  let pixelX = u32(fragmentPosition.x);
  let pixelY = u32(i32(fragmentPosition.y) - aBuffer.sliceStartY);
  return pixelY * u32(aBuffer.framebufferSize.x) + pixelX;
}

fn aBuffer_capturePremultipliedColor(
  color: vec4<f32>,
  fragmentPosition: vec4<f32>
) -> vec4<f32> {
  if (aBuffer.isActive == 0 || color.a <= 0.0) {
    return color;
  }

  let fragmentCoordinates = vec2<i32>(fragmentPosition.xy);
  let opaqueDepth = textureLoad(opaqueDepthTexture, fragmentCoordinates, 0);
  if (fragmentPosition.z >= opaqueDepth) {
    return color;
  }

  let fragmentIndex = atomicAdd(&headPointers.nextFragmentIndex, 1u);
  if (fragmentIndex >= arrayLength(&fragments.fragments)) {
    atomicAdd(&headPointers.droppedFragmentCount, 1u);
    return color;
  }

  let pixelIndex = aBuffer_getPixelIndex(fragmentPosition);
  if (pixelIndex >= arrayLength(&headPointers.heads)) {
    atomicAdd(&headPointers.droppedFragmentCount, 1u);
    return color;
  }

  let fragmentPointer = fragmentIndex + 1u;
  let nextFragmentPointer = atomicExchange(&headPointers.heads[pixelIndex], fragmentPointer);
  fragments.fragments[fragmentIndex] = ABufferFragment(
    pack4x8unorm(clamp(color, vec4<f32>(0.0), vec4<f32>(1.0))),
    fragmentPosition.z,
    nextFragmentPointer
  );
  return color;
}

fn aBuffer_captureStraightColor(
  color: vec4<f32>,
  fragmentPosition: vec4<f32>
) -> vec4<f32> {
  return aBuffer_capturePremultipliedColor(
    vec4<f32>(color.rgb * color.a, color.a),
    fragmentPosition
  );
}
`;

function getUniforms(
  props: ABufferShaderModuleProps = {},
  previousUniforms?: ABufferShaderModuleUniforms
): Partial<ABufferShaderModuleUniforms & ABufferShaderModuleBindings> {
  const uniforms = {...previousUniforms} as ABufferShaderModuleUniforms;

  if (props.isActive !== undefined) {
    uniforms.isActive = Boolean(props.isActive);
  }
  if (props.framebufferSize) {
    uniforms.framebufferSize = props.framebufferSize;
  }
  if (props.sliceStartY !== undefined) {
    uniforms.sliceStartY = props.sliceStartY;
  }

  return {
    ...uniforms,
    ...(props.headPointers ? {headPointers: props.headPointers} : {}),
    ...(props.fragments ? {fragments: props.fragments} : {}),
    ...(props.opaqueDepthTexture ? {opaqueDepthTexture: props.opaqueDepthTexture} : {})
  };
}

/**
 * WGSL shader module that appends translucent fragments to a per-pixel linked-list A-buffer.
 *
 * Fragment shaders call `aBuffer_captureStraightColor` for straight-alpha colors or
 * `aBuffer_capturePremultipliedColor` for premultiplied colors. Both helpers return the input
 * color so they can wrap an existing fragment output expression.
 */
export const aBuffer = {
  name: 'aBuffer',
  source: A_BUFFER_WGSL,
  bindingLayout: [
    {name: 'headPointers', group: 0, visibility: SHADER_STAGE_FRAGMENT},
    {name: 'fragments', group: 0, visibility: SHADER_STAGE_FRAGMENT},
    {name: 'opaqueDepthTexture', group: 0, visibility: SHADER_STAGE_FRAGMENT}
  ],
  uniformTypes: {
    isActive: 'i32',
    framebufferSize: 'vec2<f32>',
    sliceStartY: 'i32'
  },
  defaultUniforms: {
    isActive: false,
    framebufferSize: [1, 1],
    sliceStartY: 0
  },
  getUniforms
} as const satisfies ShaderModule<
  ABufferShaderModuleProps,
  ABufferShaderModuleUniforms,
  ABufferShaderModuleBindings
>;

/**
 * Shader plugin that installs the {@link aBuffer} module in WGSL models.
 *
 * Fragment shaders must still call one of the `aBuffer_capture*` helpers.
 */
export const aBufferPlugin = {
  name: 'aBuffer',
  wgsl: {
    modules: [aBuffer as ShaderModule]
  }
} as const satisfies ShaderPlugin;
