// luma.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import {type Binding} from '@luma.gl/core';
import {Computation} from '@luma.gl/engine';
import {
  GPUCommandGraph,
  GraphVectorView,
  type GraphBufferUse,
  type GraphDataView
} from './gpu-command-graph';
import {GPUScan} from './gpu-scan';
import {
  createTransientView,
  getViewBinding,
  getViewElementOffset,
  validateMatchingVectorTopology,
  validatePackedUint32View,
  validatePackedView
} from './graph-data-view-utils';

const GRID_INDEX_WORKGROUP_SIZE = 256;
const MAXIMUM_UINT32 = 0xffffffff;

/** Packed two- or three-dimensional point data accepted by {@link GPUGridIndex}. */
export type GPUGridIndexPositions =
  | GraphDataView<'float32x2'>
  | GraphVectorView<'float32x2'>
  | GraphDataView<'float32x3'>
  | GraphVectorView<'float32x3'>;

/** Optional stable object IDs aligned with {@link GPUGridIndexPositions}. */
export type GPUGridIndexSourceIds = GraphDataView<'uint32'> | GraphVectorView<'uint32'>;

/** Literal two- or three-dimensional index domain. */
export type GPUGridIndexBounds =
  | readonly [number, number, number, number]
  | readonly [number, number, number, number, number, number];

/** Two- or three-dimensional row-major grid dimensions. */
export type GPUGridIndexSize = readonly [number, number] | readonly [number, number, number];

/** Properties for one graph-native flat uniform-grid index build. */
export type GPUGridIndexProps = {
  /** Prefix for generated graph node and transient IDs. */
  id?: string;
  /** Packed point positions, optionally preserving ordered vector chunks. */
  positions: GPUGridIndexPositions;
  /** Optional stable IDs aligned with positions; logical row IDs are generated by default. */
  sourceIds?: GPUGridIndexSourceIds;
  /** First generated logical row ID. Mutually exclusive with `sourceIds`. */
  firstSourceIndex?: number;
  /** Positive integer dimensions matching the position dimension. */
  gridSize: GPUGridIndexSize;
  /** Finite inclusive domain matching the position dimension. */
  bounds: GPUGridIndexBounds;
  /** Caller-owned `cellCount + 1` exclusive offsets. */
  cellOffsets: GraphDataView<'uint32'>;
  /** Caller-owned capacity-bounded stable object IDs grouped by cell. */
  objectIds: GraphDataView<'uint32'>;
  /** Caller-owned row receiving the total number of accepted positions. */
  count: GraphDataView<'uint32'>;
  /** Caller-owned row receiving `1` when `count` exceeds object ID capacity. */
  overflow: GraphDataView<'uint32'>;
};

/**
 * Builds a flat uniform-grid index from two- or three-dimensional point positions.
 *
 * Every encoding clears and rebuilds counts, exclusive cell offsets, and capacity-bounded stable
 * object IDs. Positions outside the inclusive domain or containing non-finite components are
 * ignored. IDs within one cell have unspecified order; identity remains stable.
 */
export class GPUGridIndex {
  readonly id: string;
  readonly positions: GPUGridIndexPositions;
  readonly sourceIds?: GPUGridIndexSourceIds;
  readonly firstSourceIndex: number;
  readonly gridSize: GPUGridIndexSize;
  readonly bounds: GPUGridIndexBounds;
  readonly cellOffsets: GraphDataView<'uint32'>;
  readonly objectIds: GraphDataView<'uint32'>;
  readonly count: GraphDataView<'uint32'>;
  readonly overflow: GraphDataView<'uint32'>;
  readonly dimension: 2 | 3;
  readonly cellCount: number;
  /** Compact offsets currently require a full rebuild after any position or membership change. */
  readonly updatePolicy = 'rebuild' as const;

  constructor(props: GPUGridIndexProps) {
    this.id = props.id ?? 'gpu-grid-index';
    this.positions = props.positions;
    this.sourceIds = props.sourceIds;
    this.firstSourceIndex = props.firstSourceIndex ?? 0;
    this.gridSize = props.gridSize;
    this.bounds = props.bounds;
    this.cellOffsets = props.cellOffsets;
    this.objectIds = props.objectIds;
    this.count = props.count;
    this.overflow = props.overflow;
    this.dimension = this.positions.format === 'float32x2' ? 2 : 3;

    const positionFormat = this.dimension === 2 ? 'float32x2' : 'float32x3';
    for (const chunk of getPositionChunks(this.positions)) {
      validatePackedView(chunk, [positionFormat], `${this.id} positions`);
    }
    if (this.gridSize.length !== this.dimension || this.bounds.length !== this.dimension * 2) {
      throw new Error(`${this.id} positions, gridSize, and bounds must have matching dimensions`);
    }
    if (this.gridSize.some(size => !Number.isSafeInteger(size) || size <= 0)) {
      throw new Error(`${this.id} gridSize must contain positive integers`);
    }
    this.cellCount = this.gridSize.reduce((product, size) => product * size, 1);
    if (!Number.isSafeInteger(this.cellCount) || this.cellCount > MAXIMUM_UINT32) {
      throw new Error(`${this.id} cell count must fit in uint32`);
    }
    if (
      !this.bounds.every(Number.isFinite) ||
      Array.from({length: this.dimension}, (_, axis) => axis).some(
        axis => this.bounds[axis] > this.bounds[axis + this.dimension]
      )
    ) {
      throw new Error(`${this.id} bounds must contain finite ordered minima and maxima`);
    }

    validatePackedUint32View(this.cellOffsets, `${this.id} cellOffsets`);
    validatePackedUint32View(this.objectIds, `${this.id} objectIds`);
    validatePackedUint32View(this.count, `${this.id} count`);
    validatePackedUint32View(this.overflow, `${this.id} overflow`);
    if (this.cellOffsets.length !== this.cellCount + 1) {
      throw new Error(`${this.id} cellOffsets.length must equal cellCount + 1`);
    }
    if (this.count.length < 1 || this.overflow.length < 1) {
      throw new Error(`${this.id} count and overflow must each contain one uint32 row`);
    }
    if (this.positions.length > MAXIMUM_UINT32) {
      throw new Error(`${this.id} position count must fit in uint32`);
    }
    if (
      !Number.isSafeInteger(this.firstSourceIndex) ||
      this.firstSourceIndex < 0 ||
      this.firstSourceIndex + this.positions.length > MAXIMUM_UINT32 + 1
    ) {
      throw new Error(`${this.id} generated source IDs must fit in uint32`);
    }
    if (this.sourceIds && props.firstSourceIndex !== undefined) {
      throw new Error(`${this.id} sourceIds and firstSourceIndex are mutually exclusive`);
    }
    validateSourceIds(this.id, this.positions, this.sourceIds);
    validateDisjointGridInputs(this.id, this.positions, this.sourceIds, this.objectIds);
  }

  /** Adds a complete index rebuild to the target graph without submitting or reading back work. */
  addToGraph<Parameters>(graph: GPUCommandGraph<Parameters>): void {
    const views = [
      ...getPositionChunks(this.positions),
      ...getSourceIdChunks(this.sourceIds),
      this.cellOffsets,
      this.objectIds,
      this.count,
      this.overflow
    ];
    if (views.some(view => view.buffer.graph !== graph)) {
      throw new Error(`${this.id} views must belong to the target graph`);
    }

    const cellCounts = createTransientView(
      graph,
      `${this.id}-cell-counts`,
      'uint32',
      this.cellCount
    );
    const cellCursors = createTransientView(
      graph,
      `${this.id}-cell-cursors`,
      'uint32',
      this.cellCount
    );
    const scannedOffsets = createTransientView(
      graph,
      `${this.id}-scanned-offsets`,
      'uint32',
      this.cellCount
    );

    addInitializePass(graph, this.id, cellCounts, cellCursors);
    const positionChunks = getPositionChunks(this.positions);
    for (let chunkIndex = 0; chunkIndex < positionChunks.length; chunkIndex++) {
      const positions = positionChunks[chunkIndex];
      if (positions.length > 0) {
        addCountPass(graph, {
          id: `${this.id}-count-${chunkIndex}`,
          positions,
          cellCounts,
          gridSize: this.gridSize,
          bounds: this.bounds,
          dimension: this.dimension
        });
      }
    }
    new GPUScan({
      id: `${this.id}-scan`,
      input: cellCounts,
      output: scannedOffsets
    }).addToGraph(graph);
    addFinalizePass(graph, {
      id: `${this.id}-finalize`,
      cellCounts,
      scannedOffsets,
      cellOffsets: this.cellOffsets,
      count: this.count,
      overflow: this.overflow,
      capacity: this.objectIds.length
    });

    const sourceIdChunks = getSourceIdChunks(this.sourceIds);
    let sourceBase = this.firstSourceIndex;
    for (let chunkIndex = 0; chunkIndex < positionChunks.length; chunkIndex++) {
      const positions = positionChunks[chunkIndex];
      if (positions.length > 0 && this.objectIds.length > 0) {
        addScatterPass(graph, {
          id: `${this.id}-scatter-${chunkIndex}`,
          positions,
          sourceIds: sourceIdChunks[chunkIndex],
          sourceBase,
          scannedOffsets,
          cellCursors,
          objectIds: this.objectIds,
          gridSize: this.gridSize,
          bounds: this.bounds,
          dimension: this.dimension
        });
      }
      sourceBase += positions.length;
    }
  }
}

function addInitializePass<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  id: string,
  cellCounts: GraphDataView<'uint32'>,
  cellCursors: GraphDataView<'uint32'>
): void {
  const source = /* wgsl */ `
const CELL_COUNT: u32 = ${cellCounts.length}u;
const COUNTS_OFFSET: u32 = ${getViewElementOffset(cellCounts)}u;
const CURSORS_OFFSET: u32 = ${getViewElementOffset(cellCursors)}u;
@group(0) @binding(0) var<storage, read_write> cellCounts: array<u32>;
@group(0) @binding(1) var<storage, read_write> cellCursors: array<u32>;
@compute @workgroup_size(${GRID_INDEX_WORKGROUP_SIZE}) fn main(
  @builtin(global_invocation_id) globalId: vec3<u32>
) {
  if (globalId.x >= CELL_COUNT) { return; }
  cellCounts[COUNTS_OFFSET + globalId.x] = 0u;
  cellCursors[CURSORS_OFFSET + globalId.x] = 0u;
}`;
  addComputationPass(graph, {
    id: `${id}-initialize`,
    source,
    resources: [
      {buffer: cellCounts, usage: 'storage-write'},
      {buffer: cellCursors, usage: 'storage-write'}
    ],
    bindings: {cellCounts, cellCursors},
    dispatchCount: Math.ceil(cellCounts.length / GRID_INDEX_WORKGROUP_SIZE)
  });
}

function addCountPass<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    positions: GraphDataView<'float32x2'> | GraphDataView<'float32x3'>;
    cellCounts: GraphDataView<'uint32'>;
    gridSize: GPUGridIndexSize;
    bounds: GPUGridIndexBounds;
    dimension: 2 | 3;
  }
): void {
  const source = makePositionPassSource(
    props,
    /* wgsl */ `
  if (accepted) { atomicAdd(&cellCounts[COUNTS_OFFSET + cellIndex], 1u); }`,
    false
  );
  addComputationPass(graph, {
    id: props.id,
    source,
    resources: [
      {buffer: props.positions, usage: 'storage-read'},
      {buffer: props.cellCounts, usage: 'storage-read-write'}
    ],
    bindings: {positions: props.positions, cellCounts: props.cellCounts},
    dispatchCount: Math.ceil(props.positions.length / GRID_INDEX_WORKGROUP_SIZE)
  });
}

function addFinalizePass<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    cellCounts: GraphDataView<'uint32'>;
    scannedOffsets: GraphDataView<'uint32'>;
    cellOffsets: GraphDataView<'uint32'>;
    count: GraphDataView<'uint32'>;
    overflow: GraphDataView<'uint32'>;
    capacity: number;
  }
): void {
  const source = /* wgsl */ `
const CELL_COUNT: u32 = ${props.cellCounts.length}u;
const CAPACITY: u32 = ${props.capacity}u;
const COUNTS_OFFSET: u32 = ${getViewElementOffset(props.cellCounts)}u;
const SCANNED_OFFSET: u32 = ${getViewElementOffset(props.scannedOffsets)}u;
const OFFSETS_OFFSET: u32 = ${getViewElementOffset(props.cellOffsets)}u;
const COUNT_OFFSET: u32 = ${getViewElementOffset(props.count)}u;
const OVERFLOW_OFFSET: u32 = ${getViewElementOffset(props.overflow)}u;
@group(0) @binding(0) var<storage, read> cellCounts: array<u32>;
@group(0) @binding(1) var<storage, read> scannedOffsets: array<u32>;
@group(0) @binding(2) var<storage, read_write> cellOffsets: array<u32>;
@group(0) @binding(3) var<storage, read_write> outputCount: array<u32>;
@group(0) @binding(4) var<storage, read_write> outputOverflow: array<u32>;
@compute @workgroup_size(${GRID_INDEX_WORKGROUP_SIZE}) fn main(
  @builtin(global_invocation_id) globalId: vec3<u32>
) {
  let index = globalId.x;
  if (index < CELL_COUNT) {
    cellOffsets[OFFSETS_OFFSET + index] = scannedOffsets[SCANNED_OFFSET + index];
  }
  if (index == 0u) {
    let last = CELL_COUNT - 1u;
    let total = scannedOffsets[SCANNED_OFFSET + last] + cellCounts[COUNTS_OFFSET + last];
    cellOffsets[OFFSETS_OFFSET + CELL_COUNT] = total;
    outputCount[COUNT_OFFSET] = total;
    outputOverflow[OVERFLOW_OFFSET] = select(0u, 1u, total > CAPACITY);
  }
}`;
  addComputationPass(graph, {
    id: props.id,
    source,
    resources: [
      {buffer: props.cellCounts, usage: 'storage-read'},
      {buffer: props.scannedOffsets, usage: 'storage-read'},
      {buffer: props.cellOffsets, usage: 'storage-write'},
      {buffer: props.count, usage: 'storage-write'},
      {buffer: props.overflow, usage: 'storage-write'}
    ],
    bindings: {
      cellCounts: props.cellCounts,
      scannedOffsets: props.scannedOffsets,
      cellOffsets: props.cellOffsets,
      outputCount: props.count,
      outputOverflow: props.overflow
    },
    dispatchCount: Math.ceil(props.cellCounts.length / GRID_INDEX_WORKGROUP_SIZE)
  });
}

function addScatterPass<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    positions: GraphDataView<'float32x2'> | GraphDataView<'float32x3'>;
    sourceIds?: GraphDataView<'uint32'>;
    sourceBase: number;
    scannedOffsets: GraphDataView<'uint32'>;
    cellCursors: GraphDataView<'uint32'>;
    objectIds: GraphDataView<'uint32'>;
    gridSize: GPUGridIndexSize;
    bounds: GPUGridIndexBounds;
    dimension: 2 | 3;
  }
): void {
  const sourceIdBinding = props.sourceIds
    ? '@group(0) @binding(4) var<storage, read> sourceIds: array<u32>;'
    : '';
  const sourceId = props.sourceIds
    ? 'sourceIds[SOURCE_IDS_OFFSET + index]'
    : `${props.sourceBase}u + index`;
  const body = /* wgsl */ `
  if (accepted) {
    let cellOffset = scannedOffsets[SCANNED_OFFSET + cellIndex];
    let cellIndexOffset = atomicAdd(&cellCursors[CURSORS_OFFSET + cellIndex], 1u);
    let outputIndex = cellOffset + cellIndexOffset;
    if (outputIndex < CAPACITY) { objectIds[OBJECT_IDS_OFFSET + outputIndex] = ${sourceId}; }
  }`;
  const source = makePositionPassSource(props, body, true).replace(
    '// SOURCE_ID_BINDING',
    sourceIdBinding
  );
  const resources: GraphBufferUse[] = [
    {buffer: props.positions, usage: 'storage-read'},
    {buffer: props.scannedOffsets, usage: 'storage-read'},
    {buffer: props.cellCursors, usage: 'storage-read-write'},
    {buffer: props.objectIds, usage: 'storage-write'},
    ...(props.sourceIds
      ? ([{buffer: props.sourceIds, usage: 'storage-read'}] as GraphBufferUse[])
      : [])
  ];
  addComputationPass(graph, {
    id: props.id,
    source,
    resources,
    bindings: {
      positions: props.positions,
      scannedOffsets: props.scannedOffsets,
      cellCursors: props.cellCursors,
      objectIds: props.objectIds,
      ...(props.sourceIds ? {sourceIds: props.sourceIds} : {})
    },
    dispatchCount: Math.ceil(props.positions.length / GRID_INDEX_WORKGROUP_SIZE)
  });
}

function makePositionPassSource(
  props: {
    positions: GraphDataView<'float32x2'> | GraphDataView<'float32x3'>;
    gridSize: GPUGridIndexSize;
    bounds: GPUGridIndexBounds;
    dimension: 2 | 3;
    cellCounts?: GraphDataView<'uint32'>;
    scannedOffsets?: GraphDataView<'uint32'>;
    cellCursors?: GraphDataView<'uint32'>;
    objectIds?: GraphDataView<'uint32'>;
    sourceIds?: GraphDataView<'uint32'>;
  },
  body: string,
  scatter: boolean
): string {
  const width = props.gridSize[0];
  const height = props.gridSize[1];
  const depth = props.dimension === 3 ? props.gridSize[2] : 1;
  const maximaOffset = props.dimension;
  const zDeclarations =
    props.dimension === 3
      ? `let z = positions[POSITIONS_OFFSET + index * 3u + 2u];
    let finiteZ = z == z && abs(z) <= 3.402823466e+38;
    let inZ = z >= ${getFloatLiteral(props.bounds[2]!)} && z <= ${getFloatLiteral(props.bounds[5]!)};`
      : 'let finiteZ = true;\n    let inZ = true;';
  const zCoordinate =
    props.dimension === 3
      ? `let layer = getCoordinate(z, ${getFloatLiteral(props.bounds[2]!)}, ${getFloatLiteral(props.bounds[5]!)}, DEPTH);`
      : 'let layer = 0u;';
  const extraConstants = scatter
    ? `const SCANNED_OFFSET: u32 = ${getViewElementOffset(props.scannedOffsets!)}u;
const CURSORS_OFFSET: u32 = ${getViewElementOffset(props.cellCursors!)}u;
const OBJECT_IDS_OFFSET: u32 = ${getViewElementOffset(props.objectIds!)}u;
const CAPACITY: u32 = ${props.objectIds!.length}u;
${props.sourceIds ? `const SOURCE_IDS_OFFSET: u32 = ${getViewElementOffset(props.sourceIds)}u;` : ''}`
    : `const COUNTS_OFFSET: u32 = ${getViewElementOffset(props.cellCounts!)}u;`;
  const bindings = scatter
    ? `@group(0) @binding(1) var<storage, read> scannedOffsets: array<u32>;
@group(0) @binding(2) var<storage, read_write> cellCursors: array<atomic<u32>>;
@group(0) @binding(3) var<storage, read_write> objectIds: array<u32>;
// SOURCE_ID_BINDING`
    : '@group(0) @binding(1) var<storage, read_write> cellCounts: array<atomic<u32>>;';
  return /* wgsl */ `
const ELEMENT_COUNT: u32 = ${props.positions.length}u;
const POSITIONS_OFFSET: u32 = ${getViewElementOffset(props.positions)}u;
const WIDTH: u32 = ${width}u;
const HEIGHT: u32 = ${height}u;
const DEPTH: u32 = ${depth}u;
${extraConstants}
@group(0) @binding(0) var<storage, read> positions: array<f32>;
${bindings}

fn getCoordinate(value: f32, minimum: f32, maximum: f32, size: u32) -> u32 {
  if (maximum == minimum || value == minimum) { return 0u; }
  if (value == maximum) { return size - 1u; }
  if (minimum < 0.0 && maximum > 0.0) {
    let scaledValue = value * 0.5;
    let scaledMinimum = minimum * 0.5;
    let scaledMaximum = maximum * 0.5;
    return min(
      u32((scaledValue - scaledMinimum) / (scaledMaximum - scaledMinimum) * f32(size)),
      size - 1u
    );
  }
  return min(u32((value - minimum) / (maximum - minimum) * f32(size)), size - 1u);
}

@compute @workgroup_size(${GRID_INDEX_WORKGROUP_SIZE}) fn main(
  @builtin(global_invocation_id) globalId: vec3<u32>
) {
  let index = globalId.x;
  var accepted = false;
  var cellIndex = 0u;
  if (index < ELEMENT_COUNT) {
    let x = positions[POSITIONS_OFFSET + index * ${props.dimension}u];
    let y = positions[POSITIONS_OFFSET + index * ${props.dimension}u + 1u];
    ${zDeclarations}
    let finiteXY = x == x && y == y && abs(x) <= 3.402823466e+38 && abs(y) <= 3.402823466e+38;
    let inX = x >= ${getFloatLiteral(props.bounds[0])} && x <= ${getFloatLiteral(props.bounds[maximaOffset])};
    let inY = y >= ${getFloatLiteral(props.bounds[1])} && y <= ${getFloatLiteral(props.bounds[maximaOffset + 1])};
    if (finiteXY && finiteZ && inX && inY && inZ) {
      accepted = true;
      let column = getCoordinate(x, ${getFloatLiteral(props.bounds[0])}, ${getFloatLiteral(props.bounds[maximaOffset])}, WIDTH);
      let row = getCoordinate(y, ${getFloatLiteral(props.bounds[1])}, ${getFloatLiteral(props.bounds[maximaOffset + 1])}, HEIGHT);
      ${zCoordinate}
      cellIndex = (layer * HEIGHT + row) * WIDTH + column;
    }
  }
  ${body}
}`;
}

function addComputationPass<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    source: string;
    resources: GraphBufferUse[];
    bindings: Record<string, GraphDataView>;
    dispatchCount: number;
  }
): void {
  graph.addComputePass({
    id: props.id,
    resources: props.resources,
    compile: ({device}) => {
      const computation = new Computation(device, {
        id: props.id,
        source: props.source,
        shaderLayout: {
          bindings: Object.keys(props.bindings).map((name, location) => ({
            name,
            type: 'storage' as const,
            group: 0,
            location
          }))
        }
      });
      return {
        encode: ({computePass, getBuffer}) => {
          const bindings: Record<string, Binding> = {};
          for (const [name, view] of Object.entries(props.bindings)) {
            bindings[name] = getViewBinding(view, getBuffer);
          }
          computation.setBindings(bindings);
          computation.dispatch(computePass, props.dispatchCount);
        },
        destroy: () => computation.destroy()
      };
    }
  });
}

function validateSourceIds(
  id: string,
  positions: GPUGridIndexPositions,
  sourceIds?: GPUGridIndexSourceIds
): void {
  if (!sourceIds) return;
  for (const chunk of getSourceIdChunks(sourceIds)) {
    validatePackedUint32View(chunk, `${id} sourceIds`);
  }
  const positionsAreVector = positions instanceof GraphVectorView;
  const sourceIdsAreVector = sourceIds instanceof GraphVectorView;
  if (positionsAreVector !== sourceIdsAreVector) {
    throw new Error(`${id} positions and sourceIds must use the same view kind`);
  }
  if (positions instanceof GraphVectorView && sourceIds instanceof GraphVectorView) {
    validateMatchingVectorTopology(positions, sourceIds, `${id} sourceIds`);
  } else if (positions.length !== sourceIds.length) {
    throw new Error(`${id} sourceIds.length must equal positions.length`);
  }
}

function validateDisjointGridInputs(
  id: string,
  positions: GPUGridIndexPositions,
  sourceIds: GPUGridIndexSourceIds | undefined,
  objectIds: GraphDataView<'uint32'>
): void {
  for (const positionChunk of getPositionChunks(positions)) {
    if (doViewsOverlap(positionChunk, objectIds)) {
      throw new Error(`${id} positions and objectIds must not overlap`);
    }
  }
  for (const sourceIdChunk of getSourceIdChunks(sourceIds)) {
    if (doViewsOverlap(sourceIdChunk, objectIds)) {
      throw new Error(`${id} sourceIds and objectIds must not overlap`);
    }
  }
}

function doViewsOverlap(first: GraphDataView, second: GraphDataView): boolean {
  if (first.buffer !== second.buffer || first.length === 0 || second.length === 0) {
    return false;
  }
  const firstEnd = first.byteOffset + (first.length - 1) * first.byteStride + first.rowByteLength;
  const secondEnd =
    second.byteOffset + (second.length - 1) * second.byteStride + second.rowByteLength;
  return first.byteOffset < secondEnd && second.byteOffset < firstEnd;
}

function getPositionChunks(
  positions: GPUGridIndexPositions
): readonly (GraphDataView<'float32x2'> | GraphDataView<'float32x3'>)[] {
  return positions instanceof GraphVectorView ? positions.data : [positions];
}

function getSourceIdChunks(sourceIds?: GPUGridIndexSourceIds): readonly GraphDataView<'uint32'>[] {
  if (!sourceIds) return [];
  return sourceIds instanceof GraphVectorView ? sourceIds.data : [sourceIds];
}

function getFloatLiteral(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${value}`;
}
