/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'README',
    'whats-new', 
    {
      type: 'category',
      label: 'Upgrade Guide',
      items: [
        'upgrade-guide/upgrade-guide',
        'upgrade-guide/upgrade-to-v9',
        'upgrade-guide/upgrade-to-v9-parameters',
        'upgrade-guide/parameters2',
        'upgrade-guide/api-philosophy'
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/installing',
        'developer-guide/editing',
        'developer-guide/debugging',
        'developer-guide/testing',
        'developer-guide/profiling',
        'developer-guide/bundling',
        'developer-guide/contributing'
      ],
    },
    {
      type: 'category',
      label: 'API Guide',
      items: [
        'api-guide/README',
        'api-guide/device',
        'api-guide/resources',
        'api-guide/buffers',
        'api-guide/textures',
        'api-guide/rendering',
        'api-guide/parameters',
        'api-guide/bindings',
        'api-guide/transforms',
        'api-guide/shader-modules',
        'api-guide/webgpu-vs-webgl'
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'getting-started/README',
        'getting-started/hello-triangle',
        'getting-started/hello-instancing',
        'getting-started/hello-cube',
        'getting-started/lighting',
        'getting-started/shader-hooks',
        'getting-started/shader-modules',
        'getting-started/transform',
        'getting-started/transform-feedback',
        'getting-started/instanced-transform',
        'getting-started/external-context',
        'getting-started/whats-next'
      ]
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'category',
          label: '@luma.gl/api',
          items: [
            'api-reference/api/README',
            'api-reference/api/device',
            'api-reference/api/device-features',
            'api-reference/api/device-limits',
            'api-reference/api/canvas-context',
            'api-reference/api/parameters',
            'api-reference/api/bindings',
            'api-reference/api/types/shader-layout',
            'api-reference/api/texture-formats',
            'api-reference/api/resources/buffer',
            'api-reference/api/resources/compute-pipeline',
            'api-reference/api/resources/framebuffer',
            'api-reference/api/resources/pipeline',
            'api-reference/api/resources/render-pipeline',
            'api-reference/api/resources/sampler',
            'api-reference/api/resources/shader',
            'api-reference/api/resources/texture'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/core',
          items: [
            'api-reference/core/README'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/debug',
          items: [
            'api-reference/debug/README'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/engine',
          items: [
            'api-reference/engine/animation-loop',
            'api-reference/engine/animation/key-frames',
            'api-reference/engine/animation/timeline',
            'api-reference/engine/geometry/geometries',
            'api-reference/engine/geometry/geometry',
            'api-reference/engine/model',
            'api-reference/engine/model2',
            'api-reference/engine/pipeline-factory',
            'api-reference/engine/transform',
            'api-reference/engine/transform/buffer-transform',
            'api-reference/engine/transform/texture-transform'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/experimental',
          items: [
            'api-reference/experimental/README',
            'api-reference/experimental/gpgpu/gpu-point-in-polygon',
            'api-reference/experimental/gpgpu/histopyramid',
            'api-reference/experimental/scenegraph/group-node',
            'api-reference/experimental/scenegraph/model-node',
            'api-reference/experimental/scenegraph/scenegraph-node'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/shadertools',
          items: [
            'api-reference/shadertools/README',
            'api-reference/shadertools/assemble-shaders',
            'api-reference/shadertools/core-shader-modules',
            // 'api-reference/shadertools/effects-shader-modules',
            'api-reference/shadertools/shader-info',
            'api-reference/shadertools/shader-logs'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/test-utils',
          items: [
            'api-reference/test-utils/README',
            'api-reference/test-utils/api-reference/snapshot-test-runner',
            'api-reference/test-utils/snapshot-test-runner'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/webgl',
          items: [
            'api-reference/webgl/README',
            'api-reference/webgl/adapter/webgl-device'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/webgpu',
          items: [
            'api-reference/webgpu/README'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/constants',
          items: [
            'api-reference/constants/README'
          ]
        },
        {
          type: 'category',
          label: '@luma.gl/gltools',
          items: [
            'api-reference/gltools/README',
            'api-reference/gltools/class-list',
            'api-reference/gltools/accessors',
            'api-reference/gltools/context/context-api',
            'api-reference/gltools/context/context-properties',
            'api-reference/gltools/context/parameter-setting',
            'api-reference/gltools/context/feature-checking',
            'api-reference/gltools/context/device-pixels',
            'api-reference/gltools/parameters-legacy',
            'api-reference/gltools/classes/accessor',
            'api-reference/gltools/classes/buffer',
            'api-reference/gltools/classes/framebuffer',
            'api-reference/gltools/classes/moving-data',
            'api-reference/gltools/classes/program',
            'api-reference/gltools/classes/query',
            'api-reference/gltools/classes/renderbuffer',
            'api-reference/gltools/classes/resource',
            'api-reference/gltools/classes/shader',
            'api-reference/gltools/classes/texture',
            'api-reference/gltools/classes/texture-2d',
            'api-reference/gltools/classes/texture-3d',
            'api-reference/gltools/classes/texture-cube',
            'api-reference/gltools/classes/transform-feedback',
            'api-reference/gltools/classes/uniform-buffer-layout',
            'api-reference/gltools/classes/vertex-array',
            'api-reference/gltools/classes/vertex-array-object'
          ]
        }
      ]
    },
    'public-review',
  ]
};

module.exports = sidebars;
