// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import {type GPUCommandGraph, type GraphDataView, GraphVectorView} from './gpu-command-graph';
import {addGPUGridIndexToGraphWithDispatchLimit} from './gpu-grid-index-internals';
import {
  doGraphDataViewsOverlap,
  validateMatchingVectorTopology,
  validatePackedUint32View,
  validatePackedView
} from './graph-data-view-utils';

const MAXIMUM_UINT32 = 0xffffffff;

/** Packed two- or three-dimensional point data accepted by {@link GPUGridIndex}. */
export type GPUGridIndexPositions =
  | GraphDataView<'float32x2'>
  | GraphVectorView<'float32x2'>
  | GraphDataView<'float32x3'>
  | GraphVectorView<'float32x3'>;

/** Optional stable object IDs aligned with {@link GPUGridIndexPositions}. */
export type GPUGridIndexSourceIds = GraphDataView<'uint32'> | GraphVectorView<'uint32'>;

/** Literal two- or three-dimensional index domain. */
export type GPUGridIndexBounds =
  | readonly [number, number, number, number]
  | readonly [number, number, number, number, number, number];

/** Two- or three-dimensional row-major grid dimensions. */
export type GPUGridIndexSize = readonly [number, number] | readonly [number, number, number];

/** Properties for one graph-native flat uniform-grid index build. */
export type GPUGridIndexProps = {
  /** Prefix for generated graph node and transient IDs. */
  id?: string;
  /** Packed point positions, optionally preserving ordered vector chunks. */
  positions: GPUGridIndexPositions;
  /** Optional stable IDs aligned with positions; logical row IDs are generated by default. */
  sourceIds?: GPUGridIndexSourceIds;
  /** First generated logical row ID. Mutually exclusive with `sourceIds`. */
  firstSourceIndex?: number;
  /** Positive integer dimensions matching the position dimension. */
  gridSize: GPUGridIndexSize;
  /** Finite inclusive domain matching the position dimension. */
  bounds: GPUGridIndexBounds;
  /** Caller-owned `cellCount + 1` exclusive offsets. */
  cellOffsets: GraphDataView<'uint32'>;
  /** Caller-owned capacity-bounded stable object IDs grouped by cell. */
  objectIds: GraphDataView<'uint32'>;
  /** Caller-owned row receiving the total number of accepted positions. */
  count: GraphDataView<'uint32'>;
  /** Caller-owned row receiving `1` when `count` exceeds object ID capacity. */
  overflow: GraphDataView<'uint32'>;
};

/**
 * Builds a flat uniform-grid index from two- or three-dimensional point positions.
 *
 * Every encoding clears and rebuilds counts, exclusive cell offsets, and capacity-bounded stable
 * object IDs. Positions outside the inclusive domain or containing non-finite components are
 * ignored. IDs within one cell have unspecified order; identity remains stable.
 */
export class GPUGridIndex {
  readonly id: string;
  readonly positions: GPUGridIndexPositions;
  readonly sourceIds?: GPUGridIndexSourceIds;
  readonly firstSourceIndex: number;
  readonly gridSize: GPUGridIndexSize;
  readonly bounds: GPUGridIndexBounds;
  readonly cellOffsets: GraphDataView<'uint32'>;
  readonly objectIds: GraphDataView<'uint32'>;
  readonly count: GraphDataView<'uint32'>;
  readonly overflow: GraphDataView<'uint32'>;
  readonly dimension: 2 | 3;
  readonly cellCount: number;
  /** Compact offsets currently require a full rebuild after any position or membership change. */
  readonly updatePolicy = 'rebuild' as const;

  constructor(props: GPUGridIndexProps) {
    this.id = props.id ?? 'gpu-grid-index';
    this.positions = props.positions;
    this.sourceIds = props.sourceIds;
    this.firstSourceIndex = props.firstSourceIndex ?? 0;
    this.gridSize = props.gridSize;
    this.bounds = props.bounds;
    this.cellOffsets = props.cellOffsets;
    this.objectIds = props.objectIds;
    this.count = props.count;
    this.overflow = props.overflow;
    this.dimension = this.positions.format === 'float32x2' ? 2 : 3;

    const positionFormat = this.dimension === 2 ? 'float32x2' : 'float32x3';
    for (const chunk of getPositionChunks(this.positions)) {
      validatePackedView(chunk, [positionFormat], `${this.id} positions`);
    }
    if (this.gridSize.length !== this.dimension || this.bounds.length !== this.dimension * 2) {
      throw new Error(`${this.id} positions, gridSize, and bounds must have matching dimensions`);
    }
    if (this.gridSize.some(size => !Number.isSafeInteger(size) || size <= 0)) {
      throw new Error(`${this.id} gridSize must contain positive integers`);
    }
    this.cellCount = this.gridSize.reduce((product, size) => product * size, 1);
    if (!Number.isSafeInteger(this.cellCount) || this.cellCount > MAXIMUM_UINT32) {
      throw new Error(`${this.id} cell count must fit in uint32`);
    }
    if (
      !this.bounds.every(Number.isFinite) ||
      Array.from({length: this.dimension}, (_, axis) => axis).some(
        axis => this.bounds[axis] > this.bounds[axis + this.dimension]
      )
    ) {
      throw new Error(`${this.id} bounds must contain finite ordered minima and maxima`);
    }

    validatePackedUint32View(this.cellOffsets, `${this.id} cellOffsets`);
    validatePackedUint32View(this.objectIds, `${this.id} objectIds`);
    validatePackedUint32View(this.count, `${this.id} count`);
    validatePackedUint32View(this.overflow, `${this.id} overflow`);
    if (this.cellOffsets.length !== this.cellCount + 1) {
      throw new Error(`${this.id} cellOffsets.length must equal cellCount + 1`);
    }
    if (this.count.length < 1 || this.overflow.length < 1) {
      throw new Error(`${this.id} count and overflow must each contain one uint32 row`);
    }
    if (this.positions.length > MAXIMUM_UINT32) {
      throw new Error(`${this.id} position count must fit in uint32`);
    }
    if (
      !Number.isSafeInteger(this.firstSourceIndex) ||
      this.firstSourceIndex < 0 ||
      this.firstSourceIndex + this.positions.length > MAXIMUM_UINT32 + 1
    ) {
      throw new Error(`${this.id} generated source IDs must fit in uint32`);
    }
    if (this.sourceIds && props.firstSourceIndex !== undefined) {
      throw new Error(`${this.id} sourceIds and firstSourceIndex are mutually exclusive`);
    }
    validateSourceIds(this.id, this.positions, this.sourceIds);
    validateDisjointGridInputs(this.id, this.positions, this.sourceIds, this.objectIds);
  }

  /** Adds a complete index rebuild to the target graph without submitting or reading back work. */
  addToGraph<Parameters>(graph: GPUCommandGraph<Parameters>): void {
    addGPUGridIndexToGraphWithDispatchLimit(
      this,
      graph,
      graph.device.limits.maxComputeWorkgroupsPerDimension
    );
  }
}

function validateSourceIds(
  id: string,
  positions: GPUGridIndexPositions,
  sourceIds?: GPUGridIndexSourceIds
): void {
  if (!sourceIds) return;
  for (const chunk of getSourceIdChunks(sourceIds)) {
    validatePackedUint32View(chunk, `${id} sourceIds`);
  }
  const positionsAreVector = positions instanceof GraphVectorView;
  const sourceIdsAreVector = sourceIds instanceof GraphVectorView;
  if (positionsAreVector !== sourceIdsAreVector) {
    throw new Error(`${id} positions and sourceIds must use the same view kind`);
  }
  if (positions instanceof GraphVectorView && sourceIds instanceof GraphVectorView) {
    validateMatchingVectorTopology(positions, sourceIds, `${id} sourceIds`);
  } else if (positions.length !== sourceIds.length) {
    throw new Error(`${id} sourceIds.length must equal positions.length`);
  }
}

function validateDisjointGridInputs(
  id: string,
  positions: GPUGridIndexPositions,
  sourceIds: GPUGridIndexSourceIds | undefined,
  objectIds: GraphDataView<'uint32'>
): void {
  for (const positionChunk of getPositionChunks(positions)) {
    if (doGraphDataViewsOverlap(positionChunk, objectIds)) {
      throw new Error(`${id} positions and objectIds must not overlap`);
    }
  }
  for (const sourceIdChunk of getSourceIdChunks(sourceIds)) {
    if (doGraphDataViewsOverlap(sourceIdChunk, objectIds)) {
      throw new Error(`${id} sourceIds and objectIds must not overlap`);
    }
  }
}

function getPositionChunks(
  positions: GPUGridIndexPositions
): readonly (GraphDataView<'float32x2'> | GraphDataView<'float32x3'>)[] {
  return positions instanceof GraphVectorView ? positions.data : [positions];
}

function getSourceIdChunks(sourceIds?: GPUGridIndexSourceIds): readonly GraphDataView<'uint32'>[] {
  if (!sourceIds) return [];
  return sourceIds instanceof GraphVectorView ? sourceIds.data : [sourceIds];
}
