// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import {Buffer,type Device} from '@luma.gl/core';
import {GPUCommandGraph,type GraphDataView} from './gpu-command-graph';
import {createTransientView} from './graph-data-view-utils';
import {GPUScalarDispatchGate} from './gpu-scalar-dispatch-gate';
import {createGPUScalar,type GPUScalar} from './gpu-scalar';
import {GPUScalarCompute} from './gpu-scalar-operation';
import {GPUScalarLiteral} from './gpu-scalar-literal';
import {GPUVectorScalarMADD} from './gpu-elementwise-scalar';
import {GPUDotProductScalar} from './gpu-dot-product-scalar';
import {GPUAdaptiveSpMV} from './gpu-adaptive-spmv';
import {GPUProgramScalarOperation} from './gpu-semantic-scalar-operation';
import {GPUProgramScalarLiteral} from './gpu-semantic-state-operation';
import {GPUProgramVectorMADD,GPUProgramDotProduct} from './gpu-semantic-vector-operation';
import {GPUProgramSpMV} from './gpu-semantic-spmv';
import {setGPUComputeDispatchWorkgroups,getGPUComputeDispatchWorkgroups} from './gpu-command-dispatch-metadata';
import {GPUCompositeOperation,isGPUCommandGraphContributor,isGPUOperation,type GPUProgramOperation,type GPUOperationTree} from './gpu-operation';
import {GPUConditionalOperation,GPULoopOperation,type GPUOperationPredicate} from './gpu-control-flow-operation';
import {GPUOperationLoweringRegistry,type GPUOperationLoweringDecision,type GPUProgramBackendCapabilities} from './gpu-program-lowering';
import type {GPUProgramScalar,GPUProgramVector} from './gpu-program-value';
import type {GPUProgram} from './gpu-program';

export type GPUProgramBindings={vectors?:Readonly<Record<string,Buffer>>};
export type GPUProgramLoweredNode={nodeId:string;nodeType:'compute'|'render'|'copy';operationPath:readonly string[]};
export type GPUProgramLoweringReport={operations:readonly GPUOperationTree[];nodes:readonly GPUProgramLoweredNode[];decisions:readonly GPUOperationLoweringDecision[]};
export type GPUProgramCompilation<Parameters=void>={program:GPUProgram;graph:GPUCommandGraph<Parameters>;scalars:ReadonlyMap<string,GPUScalar>;vectors:ReadonlyMap<string,GraphDataView>;lowering:GPUProgramLoweringReport};
type LoweringState={path:string[];nodes:GPUProgramLoweredNode[];decisions:GPUOperationLoweringDecision[];predicates:GPUOperationPredicate[];scalars:Map<string,GPUScalar>;vectors:Map<string,GraphDataView>;suppressInstrumentation:boolean};

export class GPUProgramCompiler<Parameters=void>{readonly device:Device;readonly capabilities:GPUProgramBackendCapabilities;readonly lowerings=new GPUOperationLoweringRegistry<Parameters>();constructor(device:Device){this.device=device;this.capabilities=Object.freeze({backend:'webgpu',gpuConditionals:true,nativeLoops:false,childGraphs:false});this.registerCoreLowerings();}
compile(program:GPUProgram,bindings:GPUProgramBindings={}):GPUProgramCompilation<Parameters>{const graph=new GPUCommandGraph<Parameters>(this.device,{id:`${program.id}-commands`});const scalars=new Map<string,GPUScalar>();for(const scalar of program.scalars)scalars.set(scalar.id,createGPUScalar(graph,scalar.id,scalar.format));const vectors=new Map<string,GraphDataView>();for(const vector of program.vectors){if(vector.external){const buffer=bindings.vectors?.[vector.id];if(!buffer)throw new Error(`GPUProgram external vector "${vector.id}" requires a WebGPU Buffer binding`);if(buffer.byteLength<Math.max(1,vector.length)*4)throw new Error(`GPUProgram external vector "${vector.id}" buffer is too small`);const handle=graph.importBuffer({id:vector.id,byteLength:buffer.byteLength,usage:buffer.usage},buffer);vectors.set(vector.id,graph.createDataView(handle,{format:vector.format,length:vector.length}));}else vectors.set(vector.id,createTransientView(graph,vector.id,vector.format,vector.length));}const state:LoweringState={path:[],nodes:[],decisions:[],predicates:[],scalars,vectors,suppressInstrumentation:false};const restore=instrumentGraph(graph,state);try{for(const operation of program.operations)this.lower(graph,operation,state);}finally{restore();}return Object.freeze({program,graph,scalars,vectors,lowering:Object.freeze({operations:program.operationTree,nodes:Object.freeze(state.nodes.map(node=>Object.freeze({...node,operationPath:Object.freeze([...node.operationPath])}))),decisions:Object.freeze(state.decisions.map(decision=>Object.freeze({...decision})))})});}
protected registerCoreLowerings():void{
this.lowerings.register<GPUProgramScalarLiteral>('scalar-literal',(operation,context)=>{const executable=new GPUScalarLiteral({id:operation.id,output:context.resolveScalar(operation.props.output),value:operation.props.value});this.lowerWithDispatches(context.graph,[[1,1,1]],()=>executable.addToGraph(context.graph));context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'webgpu-scalar-literal',reason:'host-known literal initializes one arena scalar on GPU'});});
this.lowerings.register<GPUProgramScalarOperation>('scalar-operation',(operation,context)=>{const executable=new GPUScalarCompute({id:operation.id,operation:operation.operation,left:context.resolveScalar(operation.left),right:operation.right?context.resolveScalar(operation.right):undefined,output:context.resolveScalar(operation.output)});this.lowerWithDispatches(context.graph,[[1,1,1]],()=>executable.addToGraph(context.graph));context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'webgpu-scalar-kernel',reason:'scalar arithmetic/comparison lowers to one arena-backed workgroup'});});
this.lowerings.register<GPUProgramVectorMADD>('vector-madd',(operation,context)=>{const p=operation.props;const executable=new GPUVectorScalarMADD({id:operation.id,input:context.resolveVector(p.input),scale:context.resolveScalar(p.scale),addend:context.resolveVector(p.addend),output:context.resolveVector(p.output)});this.lowerWithDispatches(context.graph,[[Math.max(1,Math.ceil(p.output.length/256)),1,1]],()=>executable.addToGraph(context.graph));context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'webgpu-vector-madd',reason:'dense float32 MADD uses bounded WebGPU vector kernel'});});
this.lowerings.register<GPUProgramDotProduct>('dot-product',(operation,context)=>{const p=operation.props;const executable=new GPUDotProductScalar({id:operation.id,left:context.resolveVector(p.left),right:context.resolveVector(p.right),output:context.resolveScalar(p.output)});this.lowerWithDispatches(context.graph,[[1,1,1]],()=>executable.addToGraph(context.graph));context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'webgpu-fused-dot',reason:'current dot primitive reduces dense float32 vector in one workgroup'});});
this.lowerings.register<GPUProgramSpMV>('spmv',(operation,context)=>{const p=operation.props,m=p.matrix;const executable=new GPUAdaptiveSpMV({id:operation.id,rowOffsets:context.resolveVector(m.rowOffsets),columnIndices:context.resolveVector(m.columnIndices),values:context.resolveVector(m.values),vector:context.resolveVector(p.vector),output:context.resolveVector(p.output),columns:m.columns,statistics:m.statistics,strategy:p.strategy});const decision=executable.getStrategy(context.graph);let dispatches:[number,number,number][];if(decision.id==='scalar-row'||decision.id==='subgroup-row')dispatches=[[Math.ceil(m.rows/decision.details.rowsPerWorkgroup),1,1]];else if(decision.id==='workgroup-row')dispatches=[[m.rows,1,1]];else dispatches=[[m.rows*decision.details.workgroupsPerLongRow,1,1],[Math.ceil(m.rows/64),1,1]];this.lowerWithDispatches(context.graph,dispatches,()=>executable.addToGraph(context.graph));context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:`webgpu-spmv:${decision.id}`,reason:decision.reason});});
this.lowerings.register<GPUConditionalOperation>('conditional',(operation,context)=>{context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'gpu-indirect-gate',reason:'WebGPU realizes runtime predicates with zero/nonzero indirect dispatch'});for(const child of operation.operations)context.lowerConditional(operation.predicate,child);});
this.lowerings.register<GPULoopOperation>('loop',(operation,context)=>{if(!operation.predicate||operation.lowering==='unroll'){context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'bounded-unroll',reason:operation.predicate?'explicit unroll preference':'loop has no runtime predicate'});for(let i=0;i<operation.maximumIterations;i++)for(const child of operation.operations)context.lower(child);return;}context.recordDecision({operationId:operation.id,operationType:operation.type,lowering:'gpu-gated-bounded-sequence',reason:'WebGPU has indirect dispatch but no native graph loop'});for(let i=0;i<operation.maximumIterations;i++){const gated=i>=operation.minimumIterations;for(const child of operation.operations){if(gated)context.lowerConditional(operation.predicate,child);else context.lower(child);}}});}
protected lower(graph:GPUCommandGraph<Parameters>,operation:GPUProgramOperation,state:LoweringState):void{const id='id'in operation&&typeof operation.id==='string'?operation.id:operation.constructor?.name??'legacy-contributor';state.path.push(id);try{if(operation instanceof GPUCompositeOperation&&operation.type==='composite'){state.decisions.push({operationId:operation.id,operationType:operation.type,lowering:'flatten',reason:'WebGPU command graphs have no executable child-graph primitive'});for(const child of operation.operations)this.lower(graph,child,state);return;}if(isGPUOperation(operation)){const lowerer=this.lowerings.get(operation.type);if(lowerer){lowerer(operation,{graph,capabilities:this.capabilities,lower:child=>this.lower(graph,child,state),lowerConditional:(predicate,child)=>{state.predicates.push(predicate);try{this.lower(graph,child,state);}finally{state.predicates.pop();}},resolveScalar:scalar=>this.resolveScalar(scalar,state),resolveVector:vector=>this.resolveVector(vector,state),recordDecision:decision=>state.decisions.push(decision)});return;}}if(isGPUCommandGraphContributor(operation)){state.decisions.push({operationId:id,operationType:'legacy-contributor',lowering:'legacy-addToGraph',reason:'migration adapter'});operation.addToGraph(graph);return;}throw new Error(`GPUProgram operation "${id}" has no WebGPU lowering`);}finally{state.path.pop();}}
private lowerWithDispatches(graph:GPUCommandGraph<Parameters>,dispatches:[number,number,number][],callback:()=>void):void{const target=graph as any,original=target.addComputePass;let index=0;target.addComputePass=(node:any,...rest:unknown[])=>{const dispatch=dispatches[index++];if(!dispatch)throw new Error(`lowering emitted more compute nodes than declared dispatches`);return original.call(graph,setGPUComputeDispatchWorkgroups(node,dispatch),...rest);};try{callback();if(index!==dispatches.length)throw new Error(`lowering emitted ${index} compute nodes but declared ${dispatches.length} dispatches`);}finally{target.addComputePass=original;}}
private resolveScalar<T extends 'float32'|'uint32'|'sint32'>(scalar:GPUProgramScalar<T>,state:LoweringState):GPUScalar<T>{const r=state.scalars.get(scalar.id);if(!r||r.format!==scalar.format)throw new Error(`GPUProgram scalar "${scalar.id}" is not part of compilation`);return r as GPUScalar<T>;}
private resolveVector<T extends 'float32'|'uint32'|'sint32'>(vector:GPUProgramVector<T>,state:LoweringState):GraphDataView<T>{const r=state.vectors.get(vector.id);if(!r||r.format!==vector.format||r.length!==vector.length)throw new Error(`GPUProgram vector "${vector.id}" is not part of compilation`);return r as GraphDataView<T>;}}
function instrumentGraph<Parameters>(graph:GPUCommandGraph<Parameters>,state:LoweringState):()=>void{const target=graph as any,originals:Record<string,Function>={};for(const[method,nodeType]of[['addComputePass','compute'],['addRenderPass','render'],['addCopyPass','copy']]as const){const original=target[method];if(typeof original!=='function')continue;originals[method]=original;target[method]=function(node:{id:string;condition?:unknown},...rest:unknown[]){if(state.suppressInstrumentation)return original.call(graph,node,...rest);if(state.path.length)state.nodes.push({nodeId:node.id,nodeType,operationPath:[...state.path]});if(state.predicates.length){if(nodeType!=='compute')throw new Error(`runtime GPU predicate cannot condition ${nodeType} node "${node.id}"`);if(node.condition)throw new Error(`compute node "${node.id}" already has condition`);if(state.predicates.length!==1)throw new Error('nested runtime predicates require conjunction lowering');const workgroups=getGPUComputeDispatchWorkgroups(node);if(!workgroups)throw new Error(`compute node "${node.id}" under runtime predicate must declare exact dispatch geometry`);const predicate=state.predicates[0],active=state.scalars.get(predicate.value.id);if(!active||active.format!=='uint32')throw new Error(`predicate "${predicate.id}" requires uint32 scalar`);const gate=new GPUScalarDispatchGate(graph,{id:`${node.id}-predicate`,active:active as GPUScalar<'uint32'>,workgroups});state.suppressInstrumentation=true;try{gate.addUpdateToGraph(graph,`${node.id}-predicate-update`);}finally{state.suppressInstrumentation=false;}node={...node,condition:gate.condition};}return original.call(graph,node,...rest);};}return()=>{for(const[method,original]of Object.entries(originals))target[method]=original;};}
