// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import type {Binding} from '@luma.gl/core';
import {Computation} from '@luma.gl/engine';
import {GPUCommandGraph, type GraphDataView} from './gpu-command-graph';
import {getViewBinding, getViewElementOffset, validatePackedView} from './graph-data-view-utils';
import {GPUScalar, getGPUScalarWGSLStore, getGPUValueArenaWGSLBinding} from './gpu-scalar';
import type {GPUScalarDispatchGate} from './gpu-scalar-dispatch-gate';
const WORKGROUP_SIZE=256;
/** Fused float32 dot product whose scalar result is written directly into the graph value arena. */
export class GPUDotProductScalar{readonly id:string;constructor(readonly props:{id?:string;left:GraphDataView<'float32'>;right:GraphDataView<'float32'>;output:GPUScalar<'float32'>;gate?:GPUScalarDispatchGate}){this.id=props.id??'gpu-dot-product-scalar';validatePackedView(props.left,['float32'],`${this.id} left`);validatePackedView(props.right,['float32'],`${this.id} right`);if(props.left.length!==props.right.length)throw new Error(`${this.id} inputs must have equal length`);}addToGraph<Parameters>(graph:GPUCommandGraph<Parameters>):void{const{left,right,output,gate}=this.props;if(left.buffer.graph!==graph||right.buffer.graph!==graph||output.arena.graph!==(graph as unknown as GPUCommandGraph<unknown>))throw new Error(`${this.id} resources must belong to target graph`);const arenaBuffer=output.arena.buffer;const source=`const LENGTH:u32=${left.length}u;const L:u32=${getViewElementOffset(left)}u;const R:u32=${getViewElementOffset(right)}u;@group(0)@binding(0)var<storage,read>leftValues:array<f32>;@group(0)@binding(1)var<storage,read>rightValues:array<f32>;${getGPUValueArenaWGSLBinding(0,2)}var<workgroup>s:array<f32,${WORKGROUP_SIZE}>;@compute @workgroup_size(${WORKGROUP_SIZE})fn main(@builtin(local_invocation_index)lane:u32){var v=0.0;var i=lane;loop{if(i>=LENGTH){break;}v+=leftValues[L+i]*rightValues[R+i];i+=${WORKGROUP_SIZE}u;}s[lane]=v;workgroupBarrier();var stride=${WORKGROUP_SIZE/2}u;loop{if(stride==0u){break;}if(lane<stride){s[lane]+=s[lane+stride];}workgroupBarrier();stride/=2u;}if(lane==0u){${getGPUScalarWGSLStore(output,'s[0]')}}}`;graph.addComputePass({id:this.id,condition:gate?.condition,workload:{operation:'GPUDotProductScalar',commandCount:1,maximumWorkgroupCount:1,maximumInvocationCount:WORKGROUP_SIZE,readByteLength:(left.length+right.length)*4,writeByteLength:4},resources:[{buffer:left,usage:'storage-read'},{buffer:right,usage:'storage-read'},{buffer:arenaBuffer,usage:'storage-write'},...(gate?[{buffer:gate.dispatchBuffer,usage:'indirect' as const}]:[])],compile:({device})=>{const computation=new Computation(device,{id:this.id,source,shaderLayout:{bindings:[{name:'leftValues',type:'read-only-storage',group:0,location:0},{name:'rightValues',type:'read-only-storage',group:0,location:1},{name:'gpuValues',type:'storage',group:0,location:2}]}});return{encode:({computePass,getBuffer})=>{const bindings:Record<string,Binding>={leftValues:getViewBinding(left,getBuffer),rightValues:getViewBinding(right,getBuffer),gpuValues:getBuffer(arenaBuffer)};computation.setBindings(bindings);if(gate)computation.dispatchIndirect(computePass,getBuffer(gate.dispatchBuffer));else computation.dispatch(computePass,1,1,1);},destroy:()=>computation.destroy()};}});}}
