name: release

on:
  push:
    tags:
      - v*

jobs:
  check_branch:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.permitted.outputs.result }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Fetch remote branches
        run: |
          git fetch origin --depth=1

      - name: Check if on permitted branch
        id: permitted
        run: |
          result=
          branchName=$(git branch -a --contains $GITHUB_SHA | grep 'remotes/origin/' || echo "")
          if [[ $branchName == *"master" || $branchName == *"-release" ]]; then
            result=true
          fi
          echo "result=${result}" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: check_branch
    permissions:
      contents: write

    if: ${{ github.repository_owner == 'visgl' && needs.check_branch.outputs.should_build }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: volta-cli/action@2d68418f32546fd191eb666e232b321d5726484d # v4.1.1
        with:
          cache: 'yarn'

      - name: Create GitHub release entry
        run: |
          body=$(node scripts/github-release.js) &&
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/visgl/luma.gl/releases \
            -d "${body}" \
            -H "Authorization: token ${GITHUB_TOKEN}"

      - name: Login to NPM
        run: npm config set "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}"

      - name: Install dependencies
        run: yarn
      
      - name: Publish to NPM
        run: npx ocular-publish from-git
